sets.exported={
    main="Sakpata's Fists",
    range="Animator P +1",
    ammo="Automat. Oil +3",
    head="Heyoka Cap",
    body="Mpaca's Doublet",
    hands="Mpaca's Gloves",
    legs="Mpaca's Hose",
    feet="Mpaca's Boots",
    neck="Shulmanu Collar",
    waist="Moonbow Belt",
    left_ear="Enmerkar Earring",
    right_ear="Telos Earring",
    left_ring="C. Palug Ring",
    right_ring="Niqmaddu Ring",
    back={ name="Visucius's Mantle", augments={'Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20','Accuracy+20 Attack+20','Pet: Accuracy+10 Pet: Rng. Acc.+10','Pet: "Regen"+10','System: 1 ID: 1247 Val: 4',}},
}